### ISSUE TITLE
Example implementation

### ISSUE THREAD

**Issue by kushal-ti** [ImperiumMaximus/ts-lsp-client#3]
Would you perhaps consider including an example implementation of the library being used to connect to a language server, similar to https://github.com/yeger00/pylspclient/tree/master/examples?
I'm really new to LSP and even though i briefly understand the concepts, it's difficult to piece it all together. An example would be a huge help if you could include one

**Comment by WHenderson** [comment]
Just a heads up that I happen to have done what you were asking for. Check the pull requests.

**Comment by ImperiumMaximus** [comment]
Solved with #13.
Thanks for contibution and for highlighting the need of having an explicit example.
